import { Book } from "./book";

export const BOOKS: Book[] = [
  { id: 1, name: 'Terms of Enlistment (Frontlines Book 1)', 
  summary: 'The year is 2108, and the North American Commonwealth is bursting at the seams. For welfare rats like Andrew Grayson, there are only two ways out of the crime-ridden and filthy welfare tenements: You can hope to win the lottery and draw a ticket on a colony ship settling off-world... or you can join the service.', 
  author: 'Marko Kloos', review: ''  },
  { id: 2, name: 'World War Z: An Oral History of the Zombie War', 
  summary: 'We survived the zombie apocalypse, but how many of us are still haunted by that terrible time? We have (temporarily?) defeated the living dead, but at what cost? Told in the haunting and riveting voices of the men and women who witnessed the horror firsthand, World War Z is the only record of the pandemic.', 
  author: 'Max Brooks', review: '' },
  { id: 3, name: 'The Kaiju Preservation Society', 
  summary: 'When COVID-19 sweeps through New York City, Jamie Gray is stuck as a dead-end driver for food delivery apps. That is, until Jamie makes a delivery to an old acquaintance, Tom, who works at what he calls “an animal rights organization.” Tom\'s team needs a last-minute grunt to handle things on their next field visit. Jamie, eager to do anything, immediately signs on.', 
  author: 'John Scalzi', review: ''  },
  { id: 4, name: 'Paradise-1',  
  summary: 'Paradise-1. Earth\’s first deep space colony. For thousands of people, it was an opportunity for a new life. Until it went dark.', 
  author: 'Max Brooks', review: ''  },
  { id: 5, name: 'Earthlings: A Novel',  
  summary: 'Dreamlike, sometimes shocking, and always strange and wonderful, Earthlings asks what it means to be happy in a stifling world, and cements Sayaka Murata\'s status as a master chronicler of the outsider experience and our own uncanny universe.', 
  author: 'Sayaka Murata', review: ''  },
  { id: 6, name: 'Scorpio (Frontlines: Evolution Book 1)', 
  summary: 'It\'s been eight years since an alien invasion drove a small surviving group of settlers to seek refuge in an underground shelter. Cut off from the rest of humanity, the ragtag band has maintained a narrowly functioning colony due to communal effort and salvage runs. Alex Archer has her own duties as a dog handler. While this off-world colony may be harsh, Ash, Alex\'s black shepherd raised to sense threats, makes living in it a little nicer.', 
  author: 'Marko Kloos', review: ''  },
  { id: 7, name: 'Lines of Departure (Frontlines Book 2)', 
  summary: 'Vicious interstellar conflict with an indestructible alien species. Bloody civil war over the last habitable zones of the cosmos. Political unrest, militaristic police forces, dire threats to the Solar System…', 
  author: 'Marko Kloos', review: ''  },
  { id: 8, name: 'Angles of Attack (Frontlines Book 3)', 
  summary: 'The alien forces known as the Lankies are gathering on the solar systems edge, consolidating their conquest of Mars and setting their sights on Earth. The far-off colony of New Svalbard, cut off from the rest of the galaxy by the Lanky blockade, teeters on the verge of starvation and collapse. The forces of the two Earth alliances have won minor skirmishes but are in danger of losing the war. For battle-weary staff sergeant Andrew Grayson and the ragged forces of the North American Commonwealth, the fight for survival is entering a catastrophic new phase.', 
  author: 'Marko Kloos', review: ''  },
  { id: 9, name: 'Starter Villain', 
  summary: 'Charlie\'s life is going nowhere fast. A divorced substitute teacher living with his cat in a house his siblings want to sell, all he wants is to open a pub downtown, if only the bank will approve his loan. Then his long-lost uncle Jake dies and leaves his supervillain business (complete with island volcano lair) to Charlie. ', 
  author: 'John Scalzi', review: ''  },
  { id: 10, name: 'Dungeon Madness (The Divine Dungeon Book 2)', 
  summary: 'Both Cal and Dale have become stronger, each in spite of the other. The dungeon—Cal—knows exactly how much their power has increased and is working daily to become exponentially more powerful. His schemes are becoming more complex and his dungeon—his body—more deadly.', 
  author: 'Dakota Krout', review: ''  }
];